---
- name: Deploy Dashboard
  hosts: vm
  become: yes

  tasks:
    - name: Docker compose down
      command: chdir=/home/host2/Dashboard docker-compose down -v

    - name: Cleanup
      command: rm -rf /home/host2/Dashboard

    - name: Pull the Docker image from the repository
      command: docker pull raniarhaiem/nodejs:1-0

    - name: Pull the Docker image from the repository
      command: docker pull raniarhaiem/nodejs:1-0

    - name: Copy docker compose to VM
      copy:
        src: /var/jenkins_home/workspace/Dashboard/docker-compose.yml
        dest: /home/host2/Dashboard/

    - name: Execute Docker Compose
      command: chdir=/home/host2/Dashboard docker-compose up -d 
