version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
    volumes:
      - mysqldata:/var/lib/mysql

  nodejs:
    build: .
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"
    command: /bin/sh -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mysqldb:3306 -- node script.js"
    
volumes:
  mysqldata:
