version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
    volumes:
      - mysqldata:/var/lib/mysql

  mysqld-exporter:
    image: prom/mysqld-exporter
    environment:
    - DATA_SOURCE_NAME=exporter@exporterpassword/etc/my.cnf
    ports:
      - "9104:9104"
    volumes:
      - ./my.cnf:/etc/my.cnf
    command: ["--config my-cnf", "/etc/my.cnf"]

  nodejs:
    image: raniarhaiem/nodejs:latest
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"
    command: /bin/sh -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh -t 30 mysqldb:3306 -- node script.js"
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: test
volumes:
  mysqldata:
